# Use root/123 as user/password credentials
version: '3.1'

services:
    db:
        container_name: bases2-mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: bases2
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./initdb/:/docker-entrypoint-initdb.d/
        networks:
            bases2_net:
                ipv4_address: 184.18.7.10

    adminer:
        container_name: bases2-adminer
        image: adminer
        restart: always
        ports:
            - 8082:8080
        networks:
            bases2_net:
                    ipv4_address: 184.18.7.11

    api:
        image: node        
        build:
            context: .
            dockerfile: Dockerfile        
        container_name: bases2-api
        restart: on-failure
        ports:
            - 5001:5000          
        networks:
            bases2_net:
                ipv4_address: 184.18.7.12
        depends_on:
            - db
        
networks:
    bases2_net:
        ipam:
            driver: default
            config:
                - subnet: 184.18.7.0/24
